directories: [ "D:\\codes\\python\\locallistner\\test\\listener1","D:\\codes\\python\\locallistner\\test\\listener2" ]
file_patterns: [ [ ".pdf", ".docx", ".jpg", ".png" ] ]
printers: [ "Microsoft Print to PDF" ,"printer2" ]
move_directory: "D:\\codes\\python\\locallistner\\test\\moved"
